// Builds self-hosted, subset web fonts for exactly the characters used on the page.
// Re-run after editing any copy:  node tools/fonts.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(root, 'assets', 'fonts');
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36';

const sources = ['index.html', 'assets/js/interactives.js', 'assets/js/main.js'].map((f) => fs.readFileSync(path.join(root, f), 'utf8')).join('');
const ascii = Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i)).join('');
const cjk = [...new Set([...sources].filter((c) => c.codePointAt(0) > 0x7e))].join('');
const latinExtra = '—–→↑≤±−×○·’‘“”…';

const FAMILIES = [
  { family: 'Noto Serif TC', axis: 'wght', values: [300, 500, 700], text: ascii + cjk },
  { family: 'Shippori Mincho B1', axis: 'wght', values: [500, 800], text: ascii + cjk },
  { family: 'Cormorant Garamond', axis: 'ital,wght', values: ['0,300', '0,500', '1,400'], text: ascii + latinExtra },
  { family: 'IBM Plex Mono', axis: 'wght', values: [400, 500], text: ascii + latinExtra },
];

// Google honours `text=` only for short strings, so glyphs are requested in chunks.
const CHUNK = 280;

fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

let css = '/* Generated by tools/fonts.mjs — subset to the characters used on this page. */\n';
let bytes = 0;
for (const f of FAMILIES) {
  const slug = f.family.toLowerCase().replace(/\s+/g, '-');
  const chars = [...new Set([...f.text])];
  const chunks = [];
  for (let k = 0; k < chars.length; k += CHUNK) chunks.push(chars.slice(k, k + CHUNK).join(''));
  for (const v of f.values) {
    let i = 0;
    for (const chunk of chunks) {
      const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(f.family)}:${f.axis}@${v}&text=${encodeURIComponent(chunk)}&display=swap`;
      const res = await fetch(url, { headers: { 'user-agent': UA } });
      if (!res.ok) throw new Error(`${f.family} ${v}: HTTP ${res.status}`);
      const blocks = (await res.text()).match(/@font-face\s*{[^}]+}/g) || [];
      if (blocks.length !== 1) throw new Error(`${f.family} ${v}: expected 1 subset, got ${blocks.length}`);
      const block = blocks[0];
      const src = block.match(/url\((https:[^)]+)\)/)[1];
      const file = `${slug}-${String(v).replace(',', 'i')}-${i++}.woff2`;
      const buf = Buffer.from(await (await fetch(src, { headers: { 'user-agent': UA } })).arrayBuffer());
      fs.writeFileSync(path.join(outDir, file), buf);
      bytes += buf.length;
      css += block.replace(/url\(https:[^)]+\)/, `url(../fonts/${file})`).replace(/\n\s*/g, ' ') + '\n';
    }
  }
}
fs.writeFileSync(path.join(root, 'assets', 'css', 'fonts.css'), css);
console.log(`fonts: ${fs.readdirSync(outDir).length} files, ${(bytes / 1024).toFixed(0)} KB, ${cjk.length} non-ASCII glyphs`);
